name: Push Build to Artifactory
on: [workflow_dispatch]
jobs:
 build:
   runs-on: ubuntu-latest
  
   steps:
   # This action checks out the code from the repository
   - name: Checkout Code
     uses: actions/checkout@v2


   # This action sets up the JFrog CLI with the Artifactory URL and access token     
   - uses: jfrog/setup-jfrog-cli@v3
     env:
       JF_URL: ${{ secrets.ARTIFACTORY_URL }}
       JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

   # This action performs the build
   - name: Build Npm and push to Artifactory
     run: |
       cd JFTD104-Intro_to_DevSecOps_with_JFrog_Xray/lab-3/project-examples/npm-vulnerable-example
       jf npmc --repo-resolve my-npm-virtual --repo-deploy my-npm-virtual 
       jf npm install --build-name my-build --build-number 1.0.1
       jf npm publish --build-name my-build --build-number 1.0.1
       jf rt build-collect-env my-build 1.0.1
       jf rt build-add-git my-build 1.0.1

   # This action publishes the build information to Artifactory and scans the build.
   - name: Build publish and scan
     run: |
       jf rt build-publish my-build 1.0.1
       jf bs my-build 1.0.1 --vuln --fail=false
